extends SceneTree

func _init() -> void:
    var progression := MonsterProgression.new()
    progression.ensure_monster("ghost_a", "spectral", "cunning")
    var level_result: Dictionary = progression.grant_experience("ghost_a", 700)
    assert(int(level_result.level) >= 5)
    assert(progression.choose_evolution("ghost_a", "wraith"))
    assert(not progression.choose_evolution("ghost_a", "poltergeist"))
    var stats: Dictionary = progression.stat_multipliers("ghost_a")
    assert(float(stats.speed) > 1.0)

    var saved: Dictionary = progression.to_dict()
    var restored := MonsterProgression.new()
    restored.from_dict(saved)
    assert(String(restored.monsters["ghost_a"].evolution) == "wraith")

    var social := MonsterFamilyPersonality.new()
    var family: Dictionary = social.family_bonus(["spectral", "spectral", "spectral", "beast"])
    assert(float(family.speed) >= 1.2)
    assert(social.target_bias("loyal") == "treasure")
    assert(float(social.personality_modifiers("aggressive").damage) > 1.0)
    var generated_traits := social.generate_traits(42)
    var regenerated_traits := social.generate_traits(42)
    assert(generated_traits == regenerated_traits)
    assert(generated_traits.size() == 2)
    assert(String(social.personality_modifiers("fragile").category) == "negative")
    assert(String(social.personality_modifiers("cautious").category) == "mixed")
    var spectral := social.family_definition("spectral")
    assert(spectral.tags.has("ghost"))
    assert(spectral.affinity == "fog")
    assert(social.active_affinities(["spectral", "spectral"]).has("spectral"))

    var deterministic := MonsterProgression.new()
    deterministic.ensure_monster("slime_a", "ooze", "", 1234)
    var deterministic_copy := MonsterProgression.new()
    deterministic_copy.ensure_monster("slime_a", "ooze", "", 1234)
    assert(deterministic.monsters["slime_a"].traits == deterministic_copy.monsters["slime_a"].traits)
    var restored_legacy := MonsterProgression.new()
    restored_legacy.from_dict({"monsters": {"old_ghost": {"level": 2, "experience": 0, "family": "spectral", "personality": "loyal", "evolution": "base"}}})
    assert(restored_legacy.monsters["old_ghost"].traits == ["loyal"])

    print("monster progression and family test passed")
    quit()
