extends SceneTree

func _init() -> void:
	var workshop := WorkshopHub.new()
	workshop.add_resources({"payment": 2000, "materials": 500, "blueprints": 100, "reputation": 50})
	var tree := WorkshopUpgradeTree.new()
	var available := tree.available_nodes(workshop)
	assert(available.any(func(node: Dictionary) -> bool: return node.id == "contracts_extra_offer"))
	assert(not available.any(func(node: Dictionary) -> bool: return node.id == "contracts_negotiator"))
	var first := tree.unlock("contracts_extra_offer", workshop)
	assert(first.ok)
	assert(tree.unlock("contracts_negotiator", workshop).reason == "requirements")
	assert(workshop.upgrade("contracts").ok)
	var second := tree.unlock("contracts_negotiator", workshop)
	assert(second.ok)
	var effects := tree.combined_effects()
	assert(int(effects.contract_choices) == 1)
	assert(is_equal_approx(float(effects.payment_multiplier), 0.10))
	var restored := WorkshopUpgradeTree.new()
	restored.from_dict(tree.to_dict())
	assert(bool(restored.unlocked.contracts_extra_offer))
	assert(bool(restored.unlocked.contracts_negotiator))
	print("workshop upgrade tree test passed")
	quit()
